<?php

return [
    'budgetTypes' => [
        ['value' => 'Registration', 'label' => 'Registration'],
        ['value' => 'Transportation', 'label' => 'Transportation'],
        ['value' => 'Representation Allowance', 'label' => 'Representation Allowance'],
        ['value' => 'Miscellaneous', 'label' => 'Miscellaneous'],

    ],

    'budgetCharges' => [
        ['value' => 'Department Fund', 'label' => 'Department Fund'],
        ['value' => 'Departmental/Office Fund', 'label' => 'Departmental/Office Fund'],
        ['value' => 'School Fund', 'label' => 'School Fund'],

    ],


    'developers' => [
        [
            'first_name' => 'Reinhard',
            'middle_name' => 'Ugay',
            'last_name' => 'Esteban',
            'course' => 'BSIT-IV',
            'DOB' => '08/13/2001',
            'img' => "reinhard_esteban.png",
            'fb_link' => "reinhard.esteban",
            'linkedin_link' => "reinhard-esteban",
            'email' => 'rei.nhard3367@gmail.com',
            'contact_no' => '+639-66-867-4260',
        ],
        [
            'first_name' => 'Mathew Jerome',
            'middle_name' => 'Bulilan',
            'last_name' => 'Carillo',
            'course' => 'BSIT-IV',
            'DOB' => '11/04/2003',
            'img' => "mathew_carillo.png",
            'fb_link' => "yeahw0ah",
            'linkedin_link' => "kuan123x",
            'email' => 'mathewcarillo143@gmail.com',
            'contact_no' => '+639-46-606-1385'
        ],
        [
            'first_name' => 'Christoper',
            'middle_name' => 'Seguirel',
            'last_name' => 'Sab',
            'course' => 'BSIT-IV',
            'DOB' => '12/12/2000',
            'img' => "christoper_sab.png",
            'fb_link' => "christ.erst227635",
            'linkedin_link' => "sab-christoper-12a397243",
            'email' => 'christopersab@gmail.com',
            'contact_no' => '+639-38-322-9137'
        ],

        [
            'first_name' => 'John Meward',
            'middle_name' => 'Largo',
            'last_name' => 'Lanoy',
            'course' => 'BSIT-IV',
            'DOB' => '09/19/1999',
            'img' => "john_meward_lanoy.png",
            'fb_link' => "john.meward.lanoy.2024",
            'email' => 'wadelargo@gmail.com',
            'contact_no' => '+639-75-4513-486'

        ],

        [
            'first_name' => 'Joselle Ruth',
            'middle_name' => 'Badilla',
            'last_name' => 'Caingles',
            'course' => 'BSIT-IV',
            'DOB' => '03/13/2002',
            'img' => "joselle_ruth_caingles.png",
            'fb_link' => "joselle.badilla.caingles",
            'email' => 'ellesojbadilla@gmail.com',
            'contact_no' => '+639-48-615-5121'

        ],

    ],

    'specializationList' => [
        "Mathematics",
        "Science",
        "English Language Arts",
        "History",
        "Social Studies",
        "Physical Education",
        "Art",
        "Music",
        "Special Education",
        "ESL (English as a Second Language)",
        "Foreign Languages",
        "Technology Education",
        "Vocational Education",
        "Psychology",
        "Literacy",
        "Health Education",
        "Counseling",
        "Business Education",
        "Environmental Science",
        "STEM (Science, Technology, Engineering, and Mathematics)",
        "Geography",
        "Philosophy",
        "Theater Arts",
        "Home Economics",
        "Library Science",
        "Engineering",
        "Speech and Debate",
        "Computer Science",
        "Political Science",
        "Economics",
        "Anthropology",
        "Sociology",
        "Journalism",
        "Public Speaking",
        "Cultural Studies",
        "Film Studies",
        "Mathematical Logic",
        "Music Theory",
        "Dance",
        "Religious Studies",
        "Creative Writing",
        "Law",
        "Criminal Justice",
        "Marine Biology",
        "Astronomy",
        "Botany",
        "Chemistry",
        "Physics",
        "Biology",
        "Zoology",
        "Genetics",
        "Neuroscience",
        "Astronomy",
        "Robotics",
        "Artificial Intelligence",
        "Graphic Design",
        "Web Development",
        "Game Design",
        "Cybersecurity",
        "Data Science",
        "Information Technology",
        "Software Engineering",
        "Mobile App Development",
        "Database Management",
        "Networking",
        "Digital Literacy",
        "Big Data Analytics",
        "Business Intelligence",
        "E-commerce",
        "Human-Computer Interaction",
        "Cloud Architecture",
        "Operating Systems",
        "IT Project Management",
        "Ethical Hacking",
        "Software Testing",
        "Tech Entrepreneurship",
        "Digital Marketing"
    ],

    'positionList' => [
        "Finance",
        "Security",
        "Head-Guard",
        "Utility",
        "Janitor",
        "Vice President of Finance (VP)",
        "Human Resources (HR)",
        "President",
        "Vice President of Academics (VP-Academics)",
        "Maintenance",
        "Assistant Principal (AP)",
        "Teacher (T)",
        "Guidance Counselor (GC)",
        "School Nurse (SN)",
        "IT Support (IT)",
        "Admissions Officer (AO)",
        "Athletic Director (AD)",
        "Facilities Manager (FM)",
        "Marketing and Communications (M&C)",
        "Security Officer (SO)",
        "Driver",
        "Head of Drivers",
        "Bookkeeper",
        "IT Manager (ITM)",
        "Data Analyst (DA)",
        "Public Relations Officer (PRO)",
        "Event Coordinator (EC)",
        "Compliance Officer (CO)",
        "Procurement Manager (PM)",
        "Library Technician (LT)",
        "Research Coordinator (RC)",
        "Sustainability Coordinator (SC)",
        "Volunteer Coordinator (VC)",
        "Property Custodian (PC)"
    ],

    'api_key' => 'aBcDeFgHiJkLmNoPqRsTuVwXyZ123456',


];